version: '3.8'
services:
  nodoo:
    image: jiaen07/nodoo:latest
    ports:
      - "3000:3000"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"